Add more function and signal generator blocks
nasa-jpl/fastcat pull request #62
Opened 2022-12-06 08:09 UTC by kwehage

Adds new function blocks:
* Summation block, adds two or more signals together
* Multiplication block, multiplies two or more signals together
* Inversion block, inverts a single signal

Adds new signal generator blocks:
* Uniform random generator
* Gaussian random generator

2022-12-06 16:41 UTC, alex-brinkman requested changes
Great work, I like the implementation! Before we close, can I ask you add 2 more things: 

- [x] Update the `doc/fastcat_device_config_parameters.md` to document the new YAML parameters. 
- [x] Add an instance of these to the `example_configs/one_of_every_device_offline.yaml` so we can have a known working example of each

2022-12-08 22:35 UTC, kwehage commented
@alex-brinkman I think this is ready to go, let me know if you see anything else.

2022-12-09 16:57 UTC, alex-brinkman commented
I agree, nice work!

2022-12-09 16:58 UTC, alex-brinkman approved these changes

2022-12-09 16:58 UTC, merged